# Enable stateless CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: Enviar
            enabled: true
            field_name: '_csrf_token'

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
